import {
    FileText, FilePlus, FileDown, FileUp, FileSearch, FileLock, LockOpen,
    Scissors, RotateCw, Layers, Stamp, Hash, Minimize2, Shield, ShieldOff,
    Eraser, Image, FileCode, FileSpreadsheet, Presentation, BookOpen, ScanSearch,
    Globe, Wrench, PenTool, GitCompare, ShieldCheck,
    type LucideIcon,
} from 'lucide-react';

export interface Tool {
    slug: string;
    title: string;
    description: string;
    longDescription: string;
    icon: LucideIcon;
    color: string;
    gradient: string;
    apiEndpoint: string;
    acceptedTypes: string;
    category: 'convert' | 'edit' | 'security' | 'advanced';
    multiFile?: boolean;
    extraFields?: { name: string; label: string; type: string; placeholder?: string; options?: string[] }[];
}

export const tools: Tool[] = [
    // Conversion Tools
    {
        slug: 'pdf-to-word',
        title: 'PDF to Word',
        description: 'Convert your PDF documents to editable Word files instantly.',
        longDescription: 'Transform your PDF documents into fully editable Microsoft Word (.docx) files while preserving the original formatting, fonts, images, and layout. Our advanced conversion engine ensures that tables, headers, footers, and complex formatting are accurately maintained. Whether you need to edit a contract, modify a report, or update a resume, our PDF to Word converter handles it all with professional-grade accuracy. No signup required — just upload, convert, and download.',
        icon: FileText,
        color: '#2563eb',
        gradient: 'from-blue-600 to-blue-400',
        apiEndpoint: '/api/convert/pdf-to-word',
        acceptedTypes: '.pdf',
        category: 'convert',
    },
    {
        slug: 'word-to-pdf',
        title: 'Word to PDF',
        description: 'Convert Word documents to PDF format with perfect formatting.',
        longDescription: 'Convert your Microsoft Word documents (.doc, .docx) into professional PDF files. Our conversion engine preserves all formatting including fonts, images, tables, headers, and page layouts. Perfect for sharing documents that need to look the same on any device.',
        icon: FileDown,
        color: '#2563eb',
        gradient: 'from-blue-500 to-indigo-500',
        apiEndpoint: '/api/convert/word-to-pdf',
        acceptedTypes: '.doc,.docx',
        category: 'convert',
    },
    {
        slug: 'pdf-to-excel',
        title: 'PDF to Excel',
        description: 'Extract tables and data from PDF to Excel spreadsheets.',
        longDescription: 'Extract tables, data, and structured content from PDF documents into editable Excel (.xlsx) spreadsheets. Our intelligent extraction engine identifies table structures, preserves cell formatting, and maintains data accuracy. Ideal for financial reports, invoices, data analysis, and any PDF containing tabular information.',
        icon: FileSpreadsheet,
        color: '#16a34a',
        gradient: 'from-green-600 to-green-400',
        apiEndpoint: '/api/convert/pdf-to-excel',
        acceptedTypes: '.pdf',
        category: 'convert',
    },
    {
        slug: 'excel-to-pdf',
        title: 'Excel to PDF',
        description: 'Convert Excel spreadsheets to PDF format.',
        longDescription: 'Transform your Excel spreadsheets into professional PDF documents. Preserves all charts, formulas display values, formatting, and page layouts for consistent viewing across all platforms.',
        icon: FileUp,
        color: '#16a34a',
        gradient: 'from-green-500 to-emerald-500',
        apiEndpoint: '/api/convert/excel-to-pdf',
        acceptedTypes: '.xls,.xlsx',
        category: 'convert',
    },
    {
        slug: 'pdf-to-jpg',
        title: 'PDF to JPG',
        description: 'Convert PDF pages to high-quality JPG images.',
        longDescription: 'Convert each page of your PDF document into high-quality JPG images at 300 DPI resolution. Perfect for sharing PDF content on social media, embedding in presentations, or creating image previews of your documents. Our renderer ensures crisp text and vivid colors.',
        icon: Image,
        color: '#f59e0b',
        gradient: 'from-amber-500 to-yellow-400',
        apiEndpoint: '/api/convert/pdf-to-jpg',
        acceptedTypes: '.pdf',
        category: 'convert',
    },
    {
        slug: 'jpg-to-pdf',
        title: 'JPG to PDF',
        description: 'Convert JPG images to PDF documents.',
        longDescription: 'Transform your JPG and JPEG images into professional PDF documents. Combine multiple images into a single PDF or convert individual images. Perfect for creating photo albums, portfolios, or document archives.',
        icon: FileUp,
        color: '#f59e0b',
        gradient: 'from-yellow-500 to-orange-400',
        apiEndpoint: '/api/convert/jpg-to-pdf',
        acceptedTypes: '.jpg,.jpeg',
        category: 'convert',
    },
    {
        slug: 'pdf-to-png',
        title: 'PDF to PNG',
        description: 'Convert PDF pages to PNG images with transparency.',
        longDescription: 'Convert PDF pages to high-quality PNG images with support for transparency. PNG format provides lossless compression, making it ideal for documents with sharp text, logos, and graphics that need to maintain pixel-perfect quality.',
        icon: Image,
        color: '#8b5cf6',
        gradient: 'from-violet-500 to-purple-400',
        apiEndpoint: '/api/convert/pdf-to-png',
        acceptedTypes: '.pdf',
        category: 'convert',
    },
    {
        slug: 'pdf-to-html',
        title: 'PDF to HTML',
        description: 'Convert PDF documents to HTML web pages.',
        longDescription: 'Transform your PDF documents into clean, semantic HTML web pages. Our converter extracts text content and preserves the document structure, making it easy to publish PDF content on the web or integrate into existing websites.',
        icon: FileCode,
        color: '#ef4444',
        gradient: 'from-red-500 to-rose-400',
        apiEndpoint: '/api/convert/pdf-to-html',
        acceptedTypes: '.pdf',
        category: 'convert',
    },
    {
        slug: 'pdf-to-txt',
        title: 'PDF to TXT',
        description: 'Extract all text content from PDF documents.',
        longDescription: 'Extract all text content from your PDF documents into plain text (.txt) files. Our text extraction engine handles multi-column layouts, headers, footers, and complex document structures. Perfect for content analysis, text mining, or creating accessible versions of your documents.',
        icon: FileText,
        color: '#6b7280',
        gradient: 'from-gray-500 to-gray-400',
        apiEndpoint: '/api/convert/pdf-to-txt',
        acceptedTypes: '.pdf',
        category: 'convert',
    },
    {
        slug: 'pdf-to-pptx',
        title: 'PDF to PowerPoint',
        description: 'Convert PDF files to editable PowerPoint presentations.',
        longDescription: 'Convert your PDF documents into editable PowerPoint (.pptx) presentations. Each PDF page becomes a slide, with text, images, and layouts preserved for easy editing. Ideal for repurposing PDF content into presentations.',
        icon: Presentation,
        color: '#ea580c',
        gradient: 'from-orange-600 to-orange-400',
        apiEndpoint: '/api/convert/pdf-to-pptx',
        acceptedTypes: '.pdf',
        category: 'convert',
    },
    {
        slug: 'pptx-to-pdf',
        title: 'PowerPoint to PDF',
        description: 'Convert PowerPoint presentations to PDF.',
        longDescription: 'Convert your PowerPoint presentations into universally compatible PDF files. Preserves all slides, animations (as static frames), fonts, and layouts for consistent viewing on any device.',
        icon: FileDown,
        color: '#ea580c',
        gradient: 'from-orange-500 to-red-400',
        apiEndpoint: '/api/convert/pptx-to-pdf',
        acceptedTypes: '.ppt,.pptx',
        category: 'convert',
    },
    {
        slug: 'html-to-pdf',
        title: 'HTML to PDF',
        description: 'Convert HTML web pages to PDF documents.',
        longDescription: 'Transform HTML files into professional PDF documents. Our converter processes HTML structure, CSS styling, and embedded images to create high-fidelity PDF output. Perfect for archiving web content or creating printable versions of web pages.',
        icon: FileDown,
        color: '#ef4444',
        gradient: 'from-rose-500 to-pink-400',
        apiEndpoint: '/api/convert/html-to-pdf',
        acceptedTypes: '.html,.htm',
        category: 'convert',
    },
    // Editing Tools
    {
        slug: 'merge-pdf',
        title: 'Merge PDF',
        description: 'Combine multiple PDF files into a single document.',
        longDescription: 'Merge multiple PDF files into one unified document. Simply upload your PDFs, arrange them in your desired order, and combine them instantly. Our merger preserves all page content, bookmarks, and formatting. Perfect for combining reports, chapters, or any multi-part documents into a single file.',
        icon: FilePlus,
        color: '#0891b2',
        gradient: 'from-cyan-600 to-cyan-400',
        apiEndpoint: '/api/edit/merge',
        acceptedTypes: '.pdf',
        category: 'edit',
        multiFile: true,
    },
    {
        slug: 'split-pdf',
        title: 'Split PDF',
        description: 'Split a PDF into multiple separate documents.',
        longDescription: 'Split a large PDF document into smaller, more manageable files. Choose to split at specific page numbers or extract individual pages. Ideal for separating chapters, extracting specific sections, or dividing large documents for easier sharing.',
        icon: Scissors,
        color: '#0891b2',
        gradient: 'from-teal-500 to-cyan-400',
        apiEndpoint: '/api/edit/split',
        acceptedTypes: '.pdf',
        category: 'edit',
        extraFields: [{ name: 'page', label: 'Split at page', type: 'number', placeholder: '1' }],
    },
    {
        slug: 'compress-pdf',
        title: 'Compress PDF',
        description: 'Reduce PDF file size while maintaining quality.',
        longDescription: 'Reduce the file size of your PDF documents without significant quality loss. Our compression engine optimizes images, fonts, and document structure to create smaller files that are easier to share via email, upload to websites, or store in cloud services. Choose from multiple compression levels to balance size and quality.',
        icon: Minimize2,
        color: '#059669',
        gradient: 'from-emerald-600 to-emerald-400',
        apiEndpoint: '/api/edit/compress',
        acceptedTypes: '.pdf',
        category: 'edit',
    },
    {
        slug: 'rotate-pdf',
        title: 'Rotate PDF',
        description: 'Rotate PDF pages to any angle.',
        longDescription: 'Rotate individual pages or entire PDF documents by 90°, 180°, or 270°. Fix scanned documents that are sideways, correct orientation issues, or adjust page layouts. Our tool processes all pages instantly while preserving content quality.',
        icon: RotateCw,
        color: '#7c3aed',
        gradient: 'from-violet-600 to-violet-400',
        apiEndpoint: '/api/edit/rotate',
        acceptedTypes: '.pdf',
        category: 'edit',
        extraFields: [{ name: 'degrees', label: 'Rotation degrees', type: 'select', options: ['90', '180', '270'] }],
    },
    {
        slug: 'watermark-pdf',
        title: 'Add Watermark',
        description: 'Add text watermarks to your PDF documents.',
        longDescription: 'Add professional text watermarks to your PDF documents. Customize the watermark text to brand your documents, mark them as confidential, or add draft labels. The watermark is applied to every page for consistent protection.',
        icon: Stamp,
        color: '#0284c7',
        gradient: 'from-sky-600 to-sky-400',
        apiEndpoint: '/api/edit/watermark',
        acceptedTypes: '.pdf',
        category: 'edit',
        extraFields: [{ name: 'text', label: 'Watermark text', type: 'text', placeholder: 'CONFIDENTIAL' }],
    },
    {
        slug: 'reorder-pdf',
        title: 'Reorder Pages',
        description: 'Rearrange the page order in your PDF document.',
        longDescription: 'Rearrange and reorder pages within your PDF document. Specify a custom page order to reorganize content, move pages to different positions, or reverse the entire document. Perfect for restructuring reports, presentations, or any multi-page documents.',
        icon: Layers,
        color: '#d97706',
        gradient: 'from-amber-600 to-amber-400',
        apiEndpoint: '/api/edit/reorder',
        acceptedTypes: '.pdf',
        category: 'edit',
        extraFields: [{ name: 'order', label: 'Page order (e.g. 3,1,2)', type: 'text', placeholder: '3,1,2,4' }],
    },
    {
        slug: 'add-page-numbers',
        title: 'Page Numbers',
        description: 'Add page numbers to your PDF documents.',
        longDescription: 'Automatically add page numbers to every page of your PDF document. Numbers are placed at the bottom center of each page with "Page X of Y" format. Essential for professional documents, reports, and manuscripts.',
        icon: Hash,
        color: '#64748b',
        gradient: 'from-slate-500 to-slate-400',
        apiEndpoint: '/api/edit/page-numbers',
        acceptedTypes: '.pdf',
        category: 'edit',
    },
    {
        slug: 'remove-pdf-pages',
        title: 'Remove PDF Pages',
        description: 'Select and remove unwanted pages from your PDF.',
        longDescription: 'Remove specific pages from your PDF document with precision. Select individual pages, page ranges, odd/even pages, or automatically detect and remove blank pages. Preview your selections before processing to ensure accuracy. Perfect for cleaning up scanned documents, removing cover pages, or trimming unnecessary content.',
        icon: Eraser,
        color: '#f43f5e',
        gradient: 'from-rose-500 to-pink-400',
        apiEndpoint: '/api/edit/remove-pages',
        acceptedTypes: '.pdf',
        category: 'edit',
    },
    {
        slug: 'reorder-pdf-pages',
        title: 'Reorder PDF Pages',
        description: 'Drag and drop to rearrange pages in your PDF.',
        longDescription: 'Rearrange pages in your PDF document with an intuitive drag-and-drop interface. See thumbnail previews of every page, reverse the entire order, or create custom arrangements. Perfect for restructuring reports, presentations, or any multi-page documents that need reorganization.',
        icon: Layers,
        color: '#f59e0b',
        gradient: 'from-amber-500 to-orange-400',
        apiEndpoint: '/api/edit/reorder',
        acceptedTypes: '.pdf',
        category: 'edit',
    },
    {
        slug: 'organize-pdf-pages',
        title: 'Organize PDF',
        description: 'All-in-one page organizer: remove, rotate, duplicate, insert, reorder.',
        longDescription: 'The ultimate PDF page organizer combining all operations in one powerful interface. Remove unwanted pages, rotate individual pages, duplicate pages, insert blank pages, and reorder — all with drag-and-drop ease. Features multi-select, batch operations, and undo support for a professional editing experience.',
        icon: Layers,
        color: '#8b5cf6',
        gradient: 'from-violet-500 to-purple-400',
        apiEndpoint: '/api/edit/organize-pages',
        acceptedTypes: '.pdf',
        category: 'edit',
    },
    {
        slug: 'extract-pdf-pages',
        title: 'Extract PDF Pages',
        description: 'Extract selected pages into a new PDF or separate files.',
        longDescription: 'Extract specific pages from your PDF into a new document. Select individual pages or page ranges using the visual thumbnail grid, then choose to extract as a single combined PDF or as separate individual PDFs packaged in a ZIP file. Ideal for pulling specific chapters, sections, or pages from large documents.',
        icon: FileSearch,
        color: '#10b981',
        gradient: 'from-emerald-500 to-teal-400',
        apiEndpoint: '/api/edit/extract-pages',
        acceptedTypes: '.pdf',
        category: 'edit',
    },
    // Security Tools
    {
        slug: 'protect-pdf',
        title: 'Protect PDF',
        description: 'Password protect your PDF documents.',
        longDescription: 'Add strong password protection to your PDF documents with 128-bit AES encryption. Prevent unauthorized access to sensitive documents, financial reports, legal contracts, or any confidential information. Choose your own password for maximum security.',
        icon: FileLock,
        color: '#dc2626',
        gradient: 'from-red-600 to-red-400',
        apiEndpoint: '/api/security/protect',
        acceptedTypes: '.pdf',
        category: 'security',
        extraFields: [{ name: 'password', label: 'Password', type: 'password', placeholder: 'Enter password' }],
    },
    {
        slug: 'unlock-pdf',
        title: 'Unlock PDF',
        description: 'Remove password protection from PDF files.',
        longDescription: 'Remove password protection from your PDF documents. If you know the password but want to create an unprotected copy, our tool will remove all security restrictions while preserving the document content. You must provide the correct password to unlock the file.',
        icon: LockOpen,
        color: '#16a34a',
        gradient: 'from-green-600 to-green-400',
        apiEndpoint: '/api/security/unlock',
        acceptedTypes: '.pdf',
        category: 'security',
        extraFields: [{ name: 'password', label: 'Current password', type: 'password', placeholder: 'Enter password' }],
    },
    {
        slug: 'ocr-pdf',
        title: 'OCR PDF',
        description: 'Extract text from scanned PDF documents using OCR.',
        longDescription: 'Use Optical Character Recognition (OCR) to extract text from scanned PDF documents and images. Our multi-language OCR engine can recognize text in various languages and scripts, converting image-based PDFs into searchable and copyable text documents.',
        icon: ScanSearch,
        color: '#7c3aed',
        gradient: 'from-purple-600 to-violet-400',
        apiEndpoint: '/api/convert/pdf-to-txt',
        acceptedTypes: '.pdf',
        category: 'advanced',
    },
    // Advanced Tools
    {
        slug: 'pdf-to-pdfa',
        title: 'PDF to PDF/A',
        description: 'Convert PDF to archival format (PDF/A) for long-term preservation.',
        longDescription: 'Convert your PDF documents to PDF/A archival format for long-term digital preservation. PDF/A ensures your documents remain readable and accessible for decades by embedding all fonts, removing JavaScript, and adding proper metadata. Choose from PDF/A-1b (basic compliance), PDF/A-2b (improved features), or PDF/A-3b (with attachment support). Ideal for legal documents, government records, and corporate archives.',
        icon: ShieldCheck,
        color: '#0ea5e9',
        gradient: 'from-sky-500 to-cyan-400',
        apiEndpoint: '/api/convert/pdf-to-pdfa',
        acceptedTypes: '.pdf',
        category: 'advanced',
        extraFields: [
            { name: 'level', label: 'PDF/A Level', type: 'select', options: ['1b', '2b', '3b'] },
        ],
    },
    {
        slug: 'repair-pdf',
        title: 'Repair PDF',
        description: 'Fix corrupted or damaged PDF files.',
        longDescription: 'Repair damaged, corrupted, or broken PDF files that won\'t open properly. Our repair tool attempts to fix broken cross-references, rebuild document structure, remove invalid objects, and recover as many pages as possible. Works with partially damaged files, truncated downloads, and PDFs with structural errors. Upload your problematic PDF and we\'ll do our best to recover it.',
        icon: Wrench,
        color: '#f97316',
        gradient: 'from-orange-500 to-amber-400',
        apiEndpoint: '/api/edit/repair',
        acceptedTypes: '.pdf',
        category: 'advanced',
    },
    {
        slug: 'web-to-pdf',
        title: 'Web to PDF',
        description: 'Convert any webpage to a PDF document.',
        longDescription: 'Convert any webpage to a high-quality PDF document. Simply enter a URL and our tool will render the full page — including JavaScript-generated content, images, and CSS styling — into a clean PDF. Choose your preferred page size (A4 or Letter). Perfect for saving articles, documentation, receipts, and web content for offline reading or archival.',
        icon: Globe,
        color: '#6366f1',
        gradient: 'from-indigo-500 to-purple-400',
        apiEndpoint: '/api/convert/web-to-pdf',
        acceptedTypes: '',
        category: 'convert',
        extraFields: [
            { name: 'url', label: 'Webpage URL', type: 'text', placeholder: 'https://example.com' },
            { name: 'pageSize', label: 'Page Size', type: 'select', options: ['A4', 'Letter'] },
        ],
    },
    {
        slug: 'sign-pdf',
        title: 'Sign PDF',
        description: 'Add your signature to PDF documents.',
        longDescription: 'Add a visual signature to your PDF documents quickly and easily. Draw your signature, type your name for an auto-generated signature, or upload a signature image. Position your signature anywhere on any page, add your name and date, and download the signed document. Supports multiple signatures on a single document. Perfect for contracts, agreements, forms, and approvals.',
        icon: PenTool,
        color: '#8b5cf6',
        gradient: 'from-violet-500 to-purple-400',
        apiEndpoint: '/api/edit/sign',
        acceptedTypes: '.pdf',
        category: 'advanced',
    },
    {
        slug: 'compare-pdf',
        title: 'Compare PDF',
        description: 'Compare two PDF documents and find differences.',
        longDescription: 'Upload two PDF documents and get a detailed comparison report highlighting all differences. Our tool performs both text-level and visual comparison, detecting changes in content, formatting, and layout. The generated report includes a summary of differences by page, text comparison results, and visual diff overlays showing exactly where changes occurred. Ideal for reviewing document revisions, checking contract changes, and quality control.',
        icon: GitCompare,
        color: '#14b8a6',
        gradient: 'from-teal-500 to-emerald-400',
        apiEndpoint: '/api/edit/compare',
        acceptedTypes: '.pdf',
        category: 'advanced',
        multiFile: true,
    },
];

export const toolCategories = [
    { id: 'convert', label: 'Convert', description: 'Transform documents between formats' },
    { id: 'edit', label: 'Edit', description: 'Modify and enhance PDF files' },
    { id: 'security', label: 'Security', description: 'Protect and secure documents' },
    { id: 'advanced', label: 'Advanced', description: 'Professional processing tools' },
];

export function getToolBySlug(slug: string): Tool | undefined {
    return tools.find((t) => t.slug === slug);
}
